In [3]:
import nest_asyncio ## to get live stats through the internet
nest_asyncio.apply()
from understat import Understat ## database of premeir leauge
import asyncio
import json
import aiohttp ##these last 3 are helping to acsess my data


import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import matplotlib as mpl
from mplsoccer.pitch import Pitch
from mplsoccer import Radar, FontManager, grid

In [4]:
async def main():
    async with aiohttp.ClientSession() as session:
        understat = Understat(session)
        table = await understat.get_league_table("EPL", "2022")
        return table

loop = asyncio.get_event_loop()
prem_table = loop.run_until_complete(main())
prem_table

table = pd.DataFrame(data= prem_table)


table.columns = table.iloc[0]

table = table[1:]

table

,Team,M,W,D,L,G,GA,PTS,xG,NPxG,xGA,NPxGA,NPxGD,PPDA,OPPDA,DC,ODC,xPTS
1,Arsenal,24,18,3,3,52,23,57,47.91,46.39,23.57,21.28,25.1,9.64,14.27,277,111,48.7
2,Manchester City,25,17,4,4,64,25,55,57.58,53.77,23.57,21.28,32.49,10.62,24.16,309,100,55.2
3,Manchester United,24,15,4,5,41,28,49,42.68,41.15,28.36,27.6,13.55,12.42,14.0,223,166,43.04
4,Tottenham,25,14,3,8,46,35,45,37.97,35.69,30.61,29.85,5.83,13.3,13.23,170,181,39.51
5,Newcastle United,23,10,11,2,35,15,41,41.87,39.59,25.56,24.04,15.55,10.12,10.89,219,128,41.17
6,Fulham,25,11,6,8,36,31,39,33.16,27.83,46.35,44.06,-16.23,14.09,10.48,123,180,27.99
7,Liverpool,23,10,6,7,38,28,36,46.86,46.86,37.77,35.49,11.37,10.51,20.25,243,139,36.55
8,Brighton,22,10,5,7,39,29,35,41.83,39.55,26.87,22.22,17.33,9.86,16.7,209,117,40.71
9,Brentford,23,8,11,4,37,30,35,35.94,32.13,30.54,29.78,2.35,11.61,9.72,149,206,36.49
10,Chelsea,24,8,7,9,23,25,31,31.16,29.64,30.98,30.98,-1.34,8.31,13.64,172,117,33.08
11,Aston Villa,24,9,4,11,30,38,31,28.28,25.99,39.89,36.7,-10.71,12.52,10.83,148,160,29.31
12,Crystal Palace,24,6,9,9,21,31,27,24.26,22.6,37.17,36.41,-13.81,14.44,8.6,100,233,24.26
13,Nottingham Forest,24,6,7,11,18,42,25,24.04,22.52,42.15,38.34,-15.82,17.54,9.11,95,236,22.09
14,Leicester,24,7,3,14,36,42,24,26.36,24.83,37.48,35.96,-11.13,12.48,15.11,134,181,25.37
15,Wolverhampton Wanderers,24,6,6,12,18,33,24,23.3,21.78,34.22,31.94,-10.16,13.48,11.73,134,182,25.17
16,West Ham,24,6,5,13,23,29,23,32.03,27.46,27.19,24.91,2.55,16.25,12.91,111,147,35.24
17,Leeds,24,5,7,12,29,39,22,31.29,29.77,37.9,36.38,-6.61,8.61,9.69,153,150,30.31
18,Everton,24,5,6,13,17,32,21,25.73,24.97,40.6,38.32,-13.35,14.45,10.39,121,186,23.49
19,Bournemouth,24,5,6,13,22,48,21,22.11,22.11,42.92,38.35,-16.25,18.21,8.54,115,232,19.75
20,Southampton,24,5,3,16,19,41,18,23.9,23.05,34.54,33.78,-10.72,11.99,8.56,133,186,25.26